### PR TITLE
Support Red Hat

### PR DESCRIPTION
**Pull request by djjudas21**
Add support for Red Hat distros (including CentOS and Fedora) and properly support 32- and 64-bit versions of all distros.

### CODE REVIEW

**Comment by djjudas21** [comment]
Hmm well that seems to be failing a lot of checks although it worked in my testing environment. I'll have a look...

**Comment by djjudas21** [comment]
@chrisjohnson1988 do you have any idea why all these tests are failing? I've had a look and I can't really make head or tail of rspec. Thanks.

**Comment by chrisjohnson1988** [comment]
@djjudas21 Hmm, I have had a quick look and it looks like you have added quite a bit in the way of changes to the `*_spec.rb` files. Am I right in thinking that `spec/shared_contexts.rb` and `spec/spec_helper.rb` have been replaced with versions generated from a template?

[Travis.ci](https://travis-ci.org/NERC-CEH/puppet-freetds/jobs/92052813) is complaining that [this import](https://github.com/NERC-CEH/puppet-freetds/pull/3/files#diff-93830fa29d616f7c87903d08b5b1b29aR2) is not present. It would either need adding the the `Gemfile` or better still... adjusting the tests so that they fit the style of the existing tests and then reverting the changes the the helper`_spec.rb` files

**Comment by djjudas21** [comment]
Yes, I used [retrospec](https://github.com/nwops/puppet-retrospec) to generate the tests. Probably fine on a brand new set of tests but maybe not the best idea on existing tests. Let me try and undo my changes to the tests and take it from there. Thanks.

**Comment by djjudas21** [comment]
OK well reverting the automatically generated tests has at least given some sensible failure messages from Travis. I still can't figure out what's going on though - presumably I need to add cross-platform support by supplying appropriate facts, but this doesn't look trivial and I haven't written tests before.

**Comment by chrisjohnson1988** [comment]
Looks like you are pretty close. I see that you have defined a couple of platform specific contexts:

```
let(:facts) { {
  :osfamily => 'RedHat'
} }
```

Well given that the other tests should be platform independent, you will want to have a `let(:facts) {{ :osfamily => '...' }}` defined by default so that the other specs can execute correctly. You've got a couple of ways of doing this:
1. Wrap the platform independent tests in one of the platform specific contexts. This would look something like:
   
   ```
   describe 'freetds', :type => :class do
     describe 'on redhat' do
       # RedHat specific tests
     end
   
     describe 'on debian' do
   
       let(:facts) { {
         :osfamily => 'Debian'
       } }
   
       descibe 'when odbc is managed' do
         let(:params) { {
           :manage_unixodbc => true
         } }
   
         it { should contain_package('unixodbc') }
         it { should contain_package('unixodbc-dev') }
       end
   
       # Other tests here ...
     end
   end
   ```
2. You could reuse the tests by looping around the platforms.
   
   ```
   describe 'freetds', :type => :class do
     # TODO: Red hat specific tests here
     # TODO: Debian specific tests here
   
     ['Debian', 'Redhat'].each do |platform|
       describe "on #{platform}" do
   
         let(:facts) { {
           :osfamily => platform
         } }
   
         # Platform independent tests here
       end
     end
   ```

I think I prefer the later option. I have some feeling that there is a more _RSpec way_ using [shared examples](https://www.relishapp.com/rspec/rspec-core/v/2-11/docs/example-groups/shared-examples). Can't remember that off the top of my head, it has been a while since I have done this sort of testing with ruby.

**Comment by djjudas21** [comment]
Woop, got all the tests clean now - thanks for your patience. Do you want me to squash it before you merge?

**Comment by chrisjohnson1988** [comment]
That is okay... I will review the code properly when I next get chance.

**Comment by djjudas21** [comment]
Hey - any progress on this PR? Thanks

**Comment by chrisjohnson1988** [comment]
Hey @djjudas21 Sorry about the delay in this, other things have taken over.

Changes look great.

**Comment by djjudas21** [comment]
Super, thanks. No worries about the delay. Would you mind tagging a new release in GitHub and releasing to Puppet Forge? Thanks

**Comment by chrisjohnson1988** [comment]
Done and Done!

**Pull request merged**
